### ISSUE TITLE
Kan logga in utan att skriva in email eller password

### ISSUE THREAD

**Issue by ITJohan** [theman550/DAT257-K9#103]
Jag får tillbaks en token jag jag loggar in utan email eller password.

**Comment by BasharDimaria** [comment]
jag har gjort dem requeried , så det måste inte finnas sånt eller jag vet inte vad du menar

**Comment by AndreasWJ** [comment]
> jag har gjort dem requeried , så det måste inte finnas sånt eller jag vet inte vad du menar

Tror Johan menar att det inte finns någon backend validering. Till exempel, om man skickar förfrågan via Postman.

Det är backends ansvar att validera all data. På frontend så validerar vi endast för att vara användarvänliga 😄
