### ISSUE TITLE
HTTPS not active on backend

### ISSUE THREAD

**Issue by ITJohan** [theman550/DAT257-K9#54]
Blir error i netlify-versionen av appen då den använder HTTPS. Den kan inte fetcha från backend eftersom den serveras på vanlig HTTP. Får felet

> Mixed Content: The page at 'https://share-a-ride.netlify.app/trips' was loaded over HTTPS, but requested an insecure resource 'http://spilg.xyz/api/trips/'. This request has been blocked; the content must be served over HTTPS.

Går detta att fixa på AWS? @thezzern @theman550

**Comment by theman550** [comment]
Ska kika på detta, men hinner nog inte få det gjort före imorgon tyvärr
