### ISSUE TITLE
SSL verification problem

### ISSUE THREAD

**Issue by thezzern** [theman550/DAT257-K9#71]
Problem med att få alla nya komponenter att fungera. Felmeddelandet: ERR_CERT_AUTHORITY_INVALID, är konstant just nu och inga resurser fungerar. Jag och Jacob har felsökt såhär långt just nu: 
Om man inte använder https så funkar allting. Https i länkarna funkade också via postman om man har ssl verification disabled. Så där någonstans blir något galet just nu. Om någon försöker förbereda sig för demon/testa inför demon och stöter på problem just nu så är detta anledningen. Någon fix beräknas inte vara klar före sprintmötet imorgon.

**Comment by AndreasWJ** [comment]
Ah segt.
Ska vi säga så att HTTP är standard tillsvidare? Så ändrar vi på frontend till HTTPS när projektet är mer eller mindre färdigt?

**Comment by thezzern** [comment]
Kanske, om ni inte har något nytt ni gärna vill demoa, login går att demoa via postman åtminstone, bookings vet jag inte. Vi vet ungefär vad som är fel nu åtminstone, ska se ifall det går att lösa lätt imorgon, om det inte går tycker jag vi gör som du säger :)

**Comment by thezzern** [comment]
UPDATE: 
Har försökt fixa https igår tillsammans med jacob och lite idag. Har inte lyckats hitta en lösning, jag tänker inte lägga mer tid på https utan vi får köra lokalt på http eller hitta en host som stödjer http om inte någon annan vill försöka fixa det, men jag släpper https nu iaf, det är inte värt att lägga mer tid på det imo  utan vi går tillbaka till http.

**Comment by thezzern** [comment]
Stänger detta issue eftersom vi har hittat ett annat sätt att göra i login.
