### ISSUE TITLE
Uppdatera add trip

### ISSUE THREAD

**Issue by AndreasWJ** [theman550/DAT257-K9#87]
- Add modal ska stängas efter add.
- Add trip formuläret måste göra sina fält required. Det går nu att skicka in utan alla viktiga fält ifyllda
- Formatera datum rätt vid add trip, fråga backend om rätt format. Lägg till toTripResource funktion i model/Trip.js.
- Ta bort userID som krav för add trip.

**Comment by ITJohan** [comment]
Även datumformatet måste fixas? Eller är inte det ett problem längre?
